# config.yaml - 설정 예제
ocr:
  engine: easyocr  # paddleocr, easyocr, tesseract, trocr
  languages: ['ko', 'en']
  
processing:
  dpi: 200
  batch_size: 5
  max_workers: 4
  device: cpu  # cuda or cpu
  
features:
  extract_tables: true
  extract_formulas: true
  extract_financial_terms: true
  korean_nlp_enabled: true
  
output:
  formats: ['csv', 'json']
  compress: false
  save_intermediate: false
  
logging:
  level: INFO
  file: output/logs/analysis.log
